#cloud-config
hostname: k8s-b-cp
manage_etc_hosts: false
write_files:
  - path: /etc/hosts
    append: true
    content: |
      # K8s lab - all nodes
      10.30.0.10   jump-1
      10.10.0.11   k8s-a-cp
      10.10.0.21   k8s-a-w1
      10.10.0.22   k8s-a-w2
      10.20.0.11   k8s-b-cp
      10.20.0.21   k8s-b-w1
      10.20.0.22   k8s-b-w2
package_update: true
package_upgrade: false
packages:
  - python3
