[mgmt_nodes]
mgmt ansible_host=198.18.1.20 ansible_connection=local

[k8s_control]
k8s-cp ansible_host=198.18.1.21 k3s_cp_api_ip=198.18.1.21 cilium_cluster_name=flat-k3s-cilium cilium_cluster_id=1

[k8s_workers]
k8s-w1 ansible_host=198.18.1.22 k3s_cp_api_ip=198.18.1.21
k8s-w2 ansible_host=198.18.1.23 k3s_cp_api_ip=198.18.1.21

[k8s_nodes:children]
k8s_control
k8s_workers

[ubuntu_lab:children]
mgmt_nodes
k8s_nodes

[ubuntu_lab:vars]
ansible_user=cisco
ansible_ssh_pass=cisco

[all:vars]
cilium_helm_chart_version=1.19.3
cilium_cluster_pool_ipv4_cidr=10.200.0.0/16
cilium_cluster_pool_ipv4_mask_size=24
k3s_cluster_cidr=10.200.0.0/16
k3s_service_cidr=10.201.0.0/16
cilium_bgp_local_asn=65001
cilium_bgp_peer_asn=65001
cilium_bgp_peer_address=198.18.1.29
cilium_lb_pool_start=198.18.1.24
cilium_lb_pool_stop=198.18.1.28
