apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-curl-client-to-curl-target
spec:
  podSelector:
    matchLabels:
      app: curl-target
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: curl-client
